---
## NetworkManager install
- name: main / Install required network libraries
  yum: 
    name: "{{ network_packages }}"
    state: installed

## networkmanager boot
- name: main / Start NetworkManager
  systemd:
    name: NetworkManager
    state: started
    enabled: yes

## Ethernet profile
- name: main / Add ethernet connection
  nmcli:
    type: ethernet
    conn_name: "{{ item.conn_name }}"
    ifname: "{{ item.ifname }}" 
    ipv4: "{{ item.ipv4 }}"
    gw4: "{{ item.gw4 }}"
    state: present
  loop: "{{ network_ethernet }}"

## Bonding module
- name: main / Load bonding module
  modprobe:
    name: bonding
    state: present

## Bonding profile
- name: main / Add bonding connection
  nmcli:
    type: bond
    conn_name: "{{ item.conn_name }}"
    mode: "balance-rr"
    state: present
  loop: "{{ network_bond }}"
  when: ansible_bond0 is not defined

## Bonding profile modify
- name: main / Modify bonding connection
  nmcli:
    type: bond
    conn_name: "{{ item.conn_name }}"
    ipv4: "{{ item.ip4 }}"
    gw4: "{{ item.gw4 }}"
    state: present
  loop: "{{ network_bond }}"

## bonding slave
- name: main / Addbonding slave connection
  nmcli:
    type: bond-slave
    conn_name: "{{ item.conn_name }}"
    ifname: "{{ item.ifname }}"
    master: "{{ item.master }}"
    state: present
  loop: "{{ network_bond_slave }}"


