---
## Set hostname
- name: main / Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

## resolver setting
- name: main / Set resolver setting
  ini_file:
    dest: /etc/NetworkManager/NetworkManager.conf
    section: main
    option: dns
    value: none

## nsswitch.conf
- name: main / Deploy nsswitch.conf
  copy:
    src: nsswitch.conf
    dest: /etc/nsswitch.conf
    owner: root
    group: root
    mode: 0644

## resolv.conf
- name: main / Deploy resolv.conf
  copy:
    src: resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644

## hosts file
- name: main / Deploy hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

